[fix] 로직 수정 (#6)

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -8,15 +8,14 @@ on:
   push:
     branches:
       - develop
-      - main
 
 permissions:
-  contents: write
+  contents: read
   pull-requests: write
 
 jobs:
   build:
-    if: github.event_name == 'pull_request' || !contains(github.event.head_commit.message, '[skip ci]')
+    if: (github.event_name == 'pull_request') || (github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]'))
     runs-on: ubuntu-latest
 
     steps:
@@ -40,18 +39,22 @@ jobs:
 
       - name: Build the project
         id: build
+        run: pnpm build
+        continue-on-error: true
+
+      - name: Set build status
+        id: status
         run: |
-          if pnpm build; then
-            echo "status=success" >> $GITHUB_OUTPUT
+          if [ "${{ steps.build.outcome }}" == "success" ]; then
+            echo "result=success" >> $GITHUB_OUTPUT
             echo "message=빌드에 성공했습니다 🎉" >> $GITHUB_OUTPUT
           else
-            echo "status=failed" >> $GITHUB_OUTPUT
-            echo "message=빌드에 실패했습니다 😭" >> $GITHUB_OUTPUT
-            exit 1
+            echo "result=failed" >> $GITHUB_OUTPUT
+            echo "message=빌드에 실패했습니다 ❌" >> $GITHUB_OUTPUT
           fi
 
-      - name: Add bot comment to PR
-        if: success() && github.event_name == 'pull_request'
+      - name: Add comment to PR
+        if: github.event_name == 'pull_request'
         uses: actions/github-script@v6
         with:
           script: |
@@ -60,18 +63,9 @@ jobs:
               issue_number: prNumber,
               owner: context.repo.owner,
               repo: context.repo.repo,
-              body: `빌드가 성공적으로 완료되었습니다 🎉`
+              body: `### 빌드 결과\n${steps.status.outputs.message}`
             });
 
-      - name: Add failure comment to PR
-        if: failure() && github.event_name == 'pull_request'
-        uses: actions/github-script@v6
-        with:
-          script: |
-            const prNumber = context.payload.pull_request.number;
-            await github.rest.issues.createComment({
-              issue_number: prNumber,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: `빌드에 실패했습니다 ❌`
-            });
+      - name: Check build status
+        if: steps.build.outcome == 'failure'
+        run: exit 1
